### ISSUE TITLE
Anyway to give the webhook bot an icon?

### ISSUE THREAD

**Issue by mikeytown2** [jos-b/webhook-discord#16]
I know you can manually do it, was wondering if a default icon could be set in code.

**Comment by HeyItsMeNobody** [comment]
Can't you just do this in discord?..

**Comment by mikeytown2** [comment]
Yes you can do it manually do it in discord. Having it live in code would be nice.

**Comment by jos-b** [comment]
I could add this in a future release, but I think that it'd probably be for the custom webhook type.

However, I don't really feel like adding another argument to that custom function because they we are talking about quite a few arguments, which I don't like.

If this was to be implemented (which if anyone is up to doing, please feel free), `Hook.custom`'s arguments would be swapped out for an object instead, something like

```js
Hook.custom({
    "username": "My webhook",
    "message": "Blah blah",
    "color": "#FFF",
    "avatar": "link to avatar"
})
```

**Comment by jos-b** [comment]
Okay, I've just pushed version 3.0.0 to NPM. I couldn't locate the slack documentation to actually change the avatar URL. If anyone is willing to find it, please do link it here or open a PR to implement it.

I've just deprecated the custom function so it will go in the new `MessageBuilder` class, in `lib/builder.js`.

**Comment by mikeytown2** [comment]
Doesn't look too promising 
https://github.com/discordjs/discord.js/search?p=1&q=avatar&unscoped_q=avatar
